#!/bin/bash
#

java -mx2G -Dwordnet.database.dir=aux/WordNet-3.1/dict -cp dist/sim-release.jar org.goobs.sim.viz.Server aux/ontology.ser.gz aux/distsim.ser.gz 4280 &
cd viz_html && python -m SimpleHTTPServer 8000
